# Generated by Django 6.0.4 on 2026-04-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='스토리 제목')),
                ('image', models.ImageField(upload_to='stories/', verbose_name='이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
            ],
        ),
    ]
