# Generated by Django 6.0.4 on 2026-04-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='좋아요 수'),
        ),
    ]
