# Generated by Django 6.0.3 on 2026-05-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='스토리 제목')),
                ('image', models.ImageField(upload_to='stories/', verbose_name='이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('likes', models.IntegerField(default=0, verbose_name='좋아요 수')),
            ],
        ),
    ]
